version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=milestone
      - POSTGRES_PASSWORD=milestone
      - POSTGRES_DB=milestone
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

